### ISSUE TITLE
Criar cadastro do usuário

### ISSUE THREAD

**Issue by alexandrecostapb** [ifpb-santaluzia/ReitoriaItinerante#2]
- Criar activity de cadastro (tela + classe Java)
- No cadastro o usuário deve informar nome completo, campus, nível (integrado, subsequente, superior) turma (filtrar conforme o nível) e curso (filtrar conforme o nível).

**Comment by PedroLucs5** [comment]
Código base terminado, não vou dar pullrequest ainda pois preciso tirar algumas duvidas sobre a interface.

- Qual cursos são necessários ficar
- Deixar o campo de inserir nome "mais redondo"
- Não dei funcionalidade ao botão ainda
